name: mood_tracker
description: تطبيق تسجيل الحالة المزاجية اليومية - يعمل بدون إنترنت
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  timezone: any
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
